
CREATE TABLE bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V (
    EV_SUP_KEY                VARCHAR2(255),
    MSTR_SRC_STM_CD           VARCHAR2(255),
    ENT_TP_CD                 VARCHAR2(255),
    MSTR_SRC_STM_KEY          VARCHAR2(255),
    SRC_STM_CD                VARCHAR2(255),
    VLD_FROM_TMS              TIMESTAMP,
    DEL_IN_SRC_STM_IND        VARCHAR2(10),
    PCS_ISRT_ID               NUMBER(19),
    ISRT_TMS                  TIMESTAMP,
    SRC_INSTN_ISRT_ID         NUMBER(19),
    ING_ENTITY_IDENTIFIER     VARCHAR2(255),
    ID                        VARCHAR2(255),
    RECORDTYPEID_SRC          VARCHAR2(255),
    RECORDTYPE_NAME           VARCHAR2(255),
    LASTMODIFIEDDATE          VARCHAR2(50),
    LASTMODIFIEDDATE_EDC      TIMESTAMP,
    LASTMODIFIEDBYID_SRC      VARCHAR2(255),
    CREATEDDATE               VARCHAR2(50),
    CREATEDDATE_EDC           TIMESTAMP,
    CREATEDBYID_SRC           VARCHAR2(255),
    OWNERID_SRC               VARCHAR2(255),
    ACCOUNTID_SRC             VARCHAR2(255),
    WHOID_SRC                 VARCHAR2(255),
    WHATID_SRC                VARCHAR2(255),
    SUBJECT                   VARCHAR2(500),
    ING_EXTERNAL_ID_SRC       VARCHAR2(255),
    ISDELETED                 VARCHAR2(10),
    ISDELETED_EDC             NUMBER(1),
    ING_ROLE                  VARCHAR2(255),
    ING_QUALIFICATION         VARCHAR2(255),
    ING_UN_OWNER_SEGMENT      VARCHAR2(255),
    ACTIVITYDATE              VARCHAR2(50),
    ACTIVITYDATE_EDC          DATE,
    ING_PHONE_NUMBER          VARCHAR2(50),
    PRIORITY                  VARCHAR2(50),
    STATUS                    VARCHAR2(50),
    TASKSUBTYPE               VARCHAR2(50),
    TYPE                      VARCHAR2(50),
    ING_URL                   VARCHAR2(500),
    ING_TASK_NUMBER           VARCHAR2(255),
    ING_BCC_CALL_TYPE         VARCHAR2(255),
    ING_LEAD_SRC              VARCHAR2(255),
    ING_TOPIC                 VARCHAR2(255),
    ING_SUBTOPIC              VARCHAR2(255),
    ING_CALL_ORIGIN           VARCHAR2(255),
    ING_ACTIVITY_REPORT_ID    VARCHAR2(255)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10
PCTUSED 40
INITRANS 1
MAXTRANS 255
COLUMN STORE COMPRESS FOR QUERY LOW
ROW LEVEL LOCKING
LOGGING
STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    PCTINCREASE 0
    FREELISTS 1
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT
    FLASH_CACHE DEFAULT
    CELL_FLASH_CACHE DEFAULT
)
TABLESPACE bq_dry_run_17Mar;

-- COMMENTS
COMMENT ON TABLE bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V IS 'Tasks file';

COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.EV_SUP_KEY IS 'Super Key of Key table';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.MSTR_SRC_STM_CD IS 'Master Source System Code';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ENT_TP_CD IS 'Entity Type Code';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.MSTR_SRC_STM_KEY IS 'Master Source System Key';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.SRC_STM_CD IS 'Source System Code';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.VLD_FROM_TMS IS 'Valid From Timestamp';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.DEL_IN_SRC_STM_IND IS 'Deleted In Source System Indicator';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.PCS_ISRT_ID IS 'Process Insert ID';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ISRT_TMS IS 'Inserted Timestamp';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.SRC_INSTN_ISRT_ID IS 'Source Instance Insert ID';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_ENTITY_IDENTIFIER IS 'Identifies to which ING Legal Entity the party is related.';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ID IS 'ID is the unique identifier of a task within Salesforce';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.RECORDTYPEID_SRC IS 'Record Type ID determines GUI for the task';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.RECORDTYPE_NAME IS 'Record Type Name determines picklist values';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.LASTMODIFIEDDATE IS 'Last Modified DATE and time';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.CREATEDDATE IS 'Created DATE and time';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.OWNERID_SRC IS 'Assigned owner of a task';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ACCOUNTID_SRC IS 'Salesforce Account ID';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.WHOID_SRC IS 'Client Contact or Lead ID';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.WHATID_SRC IS 'Parent record ID';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.SUBJECT IS 'Subject of the task';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_EXTERNAL_ID_SRC IS 'External reference identifier';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ISDELETED IS 'Flag marking task as deleted';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_ROLE IS 'Role of task creator';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_QUALIFICATION IS 'Qualification based on Role';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_UN_OWNER_SEGMENT IS 'Owner Segment';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ACTIVITYDATE IS 'Due DATE of the task';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_PHONE_NUMBER IS 'Phone number entered by creator';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.PRIORITY IS 'Urgency of the task';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.STATUS IS 'Current state of the task';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.TASKSUBTYPE IS 'Subtype for icon display';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.TYPE IS 'Type of task: Email, Call';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_URL IS 'Clickable URL';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_TASK_NUMBER IS 'Auto-generated task number';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_BCC_CALL_TYPE IS 'Call Type details';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_LEAD_SRC IS 'Lead ID if linked';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_TOPIC IS 'Routing info for Twilio';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_SUBTOPIC IS 'Routing info for Twilio';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_CALL_ORIGIN IS 'Call reason for hotlead';
COMMENT ON COLUMN bq_dry_run_17Mar.SAL_SAC_SFO_SS_SFO_EV_TASKS_V.ING_ACTIVITY_REPORT_ID IS 'Activity Report ID linking Meetings/Tasks';